<?php
/*
 * Inventorus
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/26/2016
 */

namespace Inventorus\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ExportRequest implements JsonSerializable {
    /**
     * SteamID of user
     * @required
     * @var string $steamid public property
     */
    public $steamid;

    /**
     * Trade token of user
     * @required
     * @var string $tradeToken public property
     */
    public $tradeToken;

    /**
     * Message of trade offer
     * @optional
     * @var string $message public property
     */
    public $message;

    /**
     * Items to export
     * @required
     * @var array $items public property
     */
    public $items;

    /**
     * Success hook url
     * @optional
     * @var string $successUrl public property
     */
    public $successUrl;

    /**
     * Fail hook url
     * @optional
     * @var string $failUrl public property
     */
    public $failUrl;

    /**
     * Upate hook url
     * @optional
     * @var string $updateUrl public property
     */
    public $updateUrl;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $steamid      Initialization value for the property $this->steamid
     * @param   string            $tradeToken   Initialization value for the property $this->tradeToken
     * @param   string            $message      Initialization value for the property $this->message
     * @param   array             $items        Initialization value for the property $this->items
     * @param   string            $successUrl   Initialization value for the property $this->successUrl
     * @param   string            $failUrl      Initialization value for the property $this->failUrl
     * @param   string            $updateUrl    Initialization value for the property $this->updateUrl
     */
    public function __construct()
    {
        if(7 == func_num_args())
        {
            $this->steamid    = func_get_arg(0);
            $this->tradeToken = func_get_arg(1);
            $this->message    = func_get_arg(2);
            $this->items      = func_get_arg(3);
            $this->successUrl = func_get_arg(4);
            $this->failUrl    = func_get_arg(5);
            $this->updateUrl  = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['steamid']    = $this->steamid;
        $json['tradeToken'] = $this->tradeToken;
        $json['message']    = $this->message;
        $json['items']      = $this->items;
        $json['successUrl'] = $this->successUrl;
        $json['failUrl']    = $this->failUrl;
        $json['updateUrl']  = $this->updateUrl;

        return $json;
    }
}
