<?php
/*
 * Inventorus
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/26/2016
 */

namespace Inventorus\Http;

/**
* HTTP Methods Enumeration
*/
class HttpMethod
{
    const GET = "Get";
    const POST = "Post";
    const PUT = "Put";
    const PATCH = "Patch";
    const DELETE = "Delete";
}