<?php
/*
 * Inventorus
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/26/2016
 */

namespace Inventorus;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.inventorus.com/v1';

    /**
     * Your api key
     * @var string
     */
    /**
     * @todo Replace the $apiKey with an appropriate value
     */
    public static $apiKey = '';

}
